const capitals = [
  {
    slug: "paris",
    name: "Paris",
    country: "France",
    continent: "Europe",
    image: "/capitals/paris.jpg",
    population: "2.1 million",
    highlights: ["Eiffel Tower", "Louvre Museum", "Notre-Dame"],
    description: "The City of Light, renowned for art, fashion, gastronomy, and culture. Paris is a global center for art, fashion, and culture with iconic landmarks.",
    fullDescription: "Paris, the capital of France, is one of the most influential cities in the world. Known as the City of Light, Paris has been a beacon of culture, art, fashion, and gastronomy for centuries. The city's 19th-century cityscape is crisscrossed by wide boulevards and the River Seine. Beyond iconic landmarks like the Eiffel Tower and the 12th-century Gothic Notre-Dame cathedral, the city is known for its cafe culture and designer boutiques along the Rue du Faubourg Saint-Honoré.",
    language: "French",
    currency: "Euro (EUR)",
    timezone: "CET (UTC+1)",
    climate: "Oceanic",
    bestTimeToVisit: "April to June, September to November",
    attractions: [
      { name: "Eiffel Tower", description: "The iconic iron lattice tower on the Champ de Mars, symbol of France and one of the most recognizable structures in the world." },
      { name: "Louvre Museum", description: "The world's largest art museum and home to thousands of works including the Mona Lisa and Venus de Milo." },
      { name: "Notre-Dame Cathedral", description: "A medieval Catholic cathedral considered one of the finest examples of French Gothic architecture." },
      { name: "Champs-Élysées", description: "One of the most famous avenues in the world, known for its theaters, cafés, and luxury shops." },
      { name: "Montmartre", description: "A historic hilltop district known for the white-domed Basilica of the Sacré-Cœur and its artistic history." },
    ],
    travelTips: [
      "Purchase a Paris Museum Pass for unlimited access to over 50 museums",
      "Use the Metro for efficient transportation around the city",
      "Learn a few basic French phrases - locals appreciate the effort",
      "Visit popular attractions early morning to avoid crowds",
      "Enjoy a picnic along the Seine River for a true Parisian experience",
    ],
  },
  {
    slug: "tokyo",
    name: "Tokyo",
    country: "Japan",
    continent: "Asia",
    image: "/capitals/tokyo.jpg",
    population: "13.9 million",
    highlights: ["Shibuya Crossing", "Tokyo Tower", "Senso-ji Temple"],
    description: "A vibrant metropolis blending ultramodern and traditional, from neon-lit skyscrapers to historic temples and serene gardens.",
    fullDescription: "Tokyo, Japan's busy capital, mixes the ultramodern and the traditional, from neon-lit skyscrapers to historic temples. The opulent Meiji Shinto Shrine is known for its towering gate and surrounding woods. The Imperial Palace sits amid large public gardens. The city's many museums offer exhibits ranging from classical art to a reconstructed kabuki theater. Tokyo is also renowned for its diverse food scene, from Michelin-starred restaurants to street food stalls.",
    language: "Japanese",
    currency: "Japanese Yen (JPY)",
    timezone: "JST (UTC+9)",
    climate: "Humid subtropical",
    bestTimeToVisit: "March to May (cherry blossoms), October to November",
    attractions: [
      { name: "Shibuya Crossing", description: "The world's busiest pedestrian crossing, an iconic symbol of Tokyo's vibrant energy." },
      { name: "Tokyo Tower", description: "A communications and observation tower inspired by the Eiffel Tower, offering panoramic city views." },
      { name: "Senso-ji Temple", description: "Tokyo's oldest temple, located in Asakusa, known for its massive red lantern and traditional market street." },
      { name: "Meiji Shrine", description: "A serene Shinto shrine dedicated to Emperor Meiji, set in a beautiful forested area." },
      { name: "Akihabara", description: "The electronics and anime district, a paradise for tech enthusiasts and pop culture fans." },
    ],
    travelTips: [
      "Get a Suica or Pasmo card for convenient public transportation",
      "Respect local customs - bow when greeting, remove shoes indoors",
      "Try conveyor belt sushi (kaiten-zushi) for an affordable dining experience",
      "Visit 7-Eleven for surprisingly delicious and affordable food",
      "Book popular restaurants in advance as many require reservations",
    ],
  },
  {
    slug: "london",
    name: "London",
    country: "United Kingdom",
    continent: "Europe",
    image: "/capitals/london.jpg",
    population: "8.9 million",
    highlights: ["Big Ben", "Tower of London", "Buckingham Palace"],
    description: "A 21st-century city with history stretching back to Roman times. Royal palaces, world-class museums, and diverse neighborhoods.",
    fullDescription: "London, the capital of England and the United Kingdom, is a 21st-century city with history stretching back to Roman times. At its centre stand the imposing Houses of Parliament, the iconic 'Big Ben' clock tower and Westminster Abbey. Across the Thames River, the London Eye observation wheel provides panoramic views of the South Bank cultural complex, and the entire city. The city's diverse neighborhoods offer everything from cutting-edge fashion in Shoreditch to historic charm in Greenwich.",
    language: "English",
    currency: "British Pound (GBP)",
    timezone: "GMT (UTC+0)",
    climate: "Temperate oceanic",
    bestTimeToVisit: "May to September",
    attractions: [
      { name: "Big Ben & Parliament", description: "The iconic clock tower and seat of British government, a symbol of London worldwide." },
      { name: "Tower of London", description: "A historic castle and former royal residence, home to the Crown Jewels." },
      { name: "Buckingham Palace", description: "The official residence of the British monarch, famous for the Changing of the Guard ceremony." },
      { name: "British Museum", description: "A world-famous museum housing a vast collection of art and artifacts from around the world." },
      { name: "Tower Bridge", description: "An iconic Victorian bascule bridge spanning the River Thames." },
    ],
    travelTips: [
      "Get an Oyster card for affordable travel on public transport",
      "Many major museums are free - take advantage of this",
      "Book West End theater tickets in advance for better prices",
      "Explore different neighborhoods - each has its own character",
      "Carry an umbrella - London weather is unpredictable",
    ],
  },
  {
    slug: "rome",
    name: "Rome",
    country: "Italy",
    continent: "Europe",
    image: "/capitals/rome.jpg",
    population: "2.8 million",
    highlights: ["Colosseum", "Vatican City", "Trevi Fountain"],
    description: "The Eternal City, where ancient ruins and Renaissance masterpieces meet modern Italian culture and world-famous cuisine.",
    fullDescription: "Rome, Italy's capital, is a sprawling, cosmopolitan city with nearly 3,000 years of globally influential art, architecture and culture on display. Ancient ruins such as the Forum and the Colosseum evoke the power of the former Roman Empire. Vatican City, headquarters of the Roman Catholic Church, has St. Peter's Basilica and the Vatican Museums, which house masterpieces such as Michelangelo's Sistine Chapel frescoes. The city seamlessly blends its ancient past with vibrant modern Italian life.",
    language: "Italian",
    currency: "Euro (EUR)",
    timezone: "CET (UTC+1)",
    climate: "Mediterranean",
    bestTimeToVisit: "April to June, September to October",
    attractions: [
      { name: "Colosseum", description: "The iconic ancient amphitheater, once hosting gladiatorial contests and public spectacles." },
      { name: "Vatican City", description: "The world's smallest country, home to St. Peter's Basilica and the Sistine Chapel." },
      { name: "Trevi Fountain", description: "A stunning Baroque fountain where tradition says tossing a coin ensures your return to Rome." },
      { name: "Roman Forum", description: "The ancient heart of Rome, featuring ruins of important government buildings." },
      { name: "Pantheon", description: "A remarkably preserved ancient Roman temple with its famous oculus dome." },
    ],
    travelTips: [
      "Book Vatican and Colosseum tickets online to skip the long lines",
      "Dress modestly when visiting churches - covered shoulders and knees required",
      "Enjoy aperitivo hour for drinks with complimentary snacks",
      "Be wary of tourist trap restaurants near major attractions",
      "Take a day trip to Tivoli or Ostia Antica for a change of pace",
    ],
  },
  {
    slug: "berlin",
    name: "Berlin",
    country: "Germany",
    continent: "Europe",
    image: "/capitals/berlin.jpg",
    population: "3.6 million",
    highlights: ["Brandenburg Gate", "Berlin Wall", "Museum Island"],
    description: "A city of culture, politics, and reinvention. Berlin is known for its art scene, nightlife, and modern architecture.",
    fullDescription: "Berlin, Germany's capital, dates to the 13th century. Reminders of the city's turbulent 20th-century history include its Holocaust memorial and the Berlin Wall's graffitied remains. Divided during the Cold War, its 18th-century Brandenburg Gate has become a symbol of reunification. The city's also known for its art scene and modern landmarks like the gold-colored, swoop-roofed Berliner Philharmonie. Berlin has reinvented itself as a center of creativity, known for its vibrant nightlife, diverse food scene, and thriving art galleries.",
    language: "German",
    currency: "Euro (EUR)",
    timezone: "CET (UTC+1)",
    climate: "Oceanic",
    bestTimeToVisit: "May to September",
    attractions: [
      { name: "Brandenburg Gate", description: "An 18th-century neoclassical monument, symbol of German unity and European peace." },
      { name: "Berlin Wall Memorial", description: "A preserved section of the wall with documentation center about the divided city." },
      { name: "Museum Island", description: "A UNESCO World Heritage site featuring five world-renowned museums." },
      { name: "Reichstag Building", description: "The historic parliament building with a stunning modern glass dome offering city views." },
      { name: "East Side Gallery", description: "The longest remaining section of the Berlin Wall, covered in murals by artists from around the world." },
    ],
    travelTips: [
      "Get a Berlin WelcomeCard for public transport and attraction discounts",
      "Explore neighborhoods by bike - Berlin is very bicycle-friendly",
      "Experience the nightlife - clubs often stay open until late morning",
      "Try currywurst, the city's iconic street food",
      "Visit flea markets on weekends for unique finds",
    ],
  },
  {
    slug: "madrid",
    name: "Madrid",
    country: "Spain",
    continent: "Europe",
    image: "/capitals/madrid.jpg",
    population: "3.2 million",
    highlights: ["Royal Palace", "Prado Museum", "Puerta del Sol"],
    description: "Spain's vibrant capital, famous for its royal palace, world-class art museums, and legendary nightlife scene.",
    fullDescription: "Madrid, Spain's central capital, is a city of elegant boulevards and expansive, manicured parks such as the Buen Retiro. It's renowned for its rich repositories of European art, including the Prado Museum's works by Velázquez and Goya. The heart of old Hapsburg Madrid is the portico-lined Plaza Mayor, and nearby is the baroque Royal Palace and Armory. The city pulses with energy, from its legendary nightlife that starts past midnight to its bustling tapas bars and traditional flamenco venues.",
    language: "Spanish",
    currency: "Euro (EUR)",
    timezone: "CET (UTC+1)",
    climate: "Mediterranean",
    bestTimeToVisit: "March to May, September to November",
    attractions: [
      { name: "Royal Palace", description: "The official residence of the Spanish Royal Family, featuring stunning Baroque architecture." },
      { name: "Prado Museum", description: "One of the world's greatest art museums, housing masterpieces by Velázquez, Goya, and El Greco." },
      { name: "Puerta del Sol", description: "The central square and heart of Madrid, marking kilometer zero of Spain's road network." },
      { name: "Retiro Park", description: "A beautiful 350-acre park perfect for rowing, picnicking, and visiting the Crystal Palace." },
      { name: "Plaza Mayor", description: "A grand 17th-century square surrounded by three-story residential buildings with restaurants and shops." },
    ],
    travelTips: [
      "Adapt to Spanish meal times - lunch at 2pm, dinner after 9pm",
      "Experience tapas hopping in La Latina neighborhood",
      "Visit the Prado on Sunday afternoons for free admission",
      "Take a day trip to Toledo or Segovia for historic charm",
      "Catch a flamenco show for an authentic Spanish experience",
    ],
  },
  {
    slug: "washington-dc",
    name: "Washington D.C.",
    country: "United States",
    continent: "North America",
    image: "/capitals/washington.jpg",
    population: "0.7 million",
    highlights: ["White House", "Lincoln Memorial", "Smithsonian"],
    description: "The capital of the United States, home to iconic monuments, world-renowned museums, and the seat of American government.",
    fullDescription: "Washington, DC, the U.S. capital, is a compact city on the Potomac River, bordering the states of Maryland and Virginia. It's defined by imposing neoclassical monuments and buildings, including the iconic ones that house the federal government's 3 branches: the Capitol, White House and Supreme Court. It's also home to iconic museums like the Smithsonian Institution, most of which offer free admission. The National Mall, a large open park, connects many of the city's monuments and museums.",
    language: "English",
    currency: "US Dollar (USD)",
    timezone: "EST (UTC-5)",
    climate: "Humid subtropical",
    bestTimeToVisit: "March to May (cherry blossoms), September to November",
    attractions: [
      { name: "White House", description: "The official residence and workplace of the President of the United States." },
      { name: "Lincoln Memorial", description: "An iconic monument honoring the 16th President, featuring a large seated sculpture." },
      { name: "Smithsonian Museums", description: "A collection of 19 world-class museums and galleries, all with free admission." },
      { name: "National Mall", description: "A two-mile stretch of parkland connecting the Capitol to the Lincoln Memorial." },
      { name: "Washington Monument", description: "An obelisk honoring George Washington, offering panoramic views from its observation deck." },
    ],
    travelTips: [
      "Take advantage of free admission to all Smithsonian museums",
      "Book White House and Capitol tours well in advance through your congressional representative",
      "Use the Metro system - it's clean and efficient",
      "Visit during cherry blossom season (late March/early April) for stunning views",
      "Explore Georgetown for shopping, dining, and historic architecture",
    ],
  },
]

export default capitals

export function getCapitalBySlug(slug) {
  return capitals.find((capital) => capital.slug === slug)
}

export function getAllCapitalSlugs() {
  return capitals.map((capital) => capital.slug)
}
